apiVersion: v1
kind: Pod

metadata:
  name: image-pull-lab
  labels:
    app: image-pull-lab

spec:
  containers:
    - name: web
      image: nginx:1.999-lab
      imagePullPolicy: Always

      ports:
        - containerPort: 80
