apiVersion: v1
data:
  tls.crt: REPLACE_WITH_BASE64_CERTIFICATE
  tls.key: REPLACE_WITH_BASE64_PRIVATE_KEY
kind: Secret
metadata:
  name: hostname-mismatch-tls
  namespace: tls-lab-07
type: kubernetes.io/tls
