apiVersion: v1
kind: Service
metadata:
  name: routing-demo-service
  namespace: ingress-routing-lab
spec:
  selector:
    app: routing-demo
  ports:
    - name: http
      port: 80
      targetPort: http
