apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-example
  template:
    metadata:
      labels:
        app: resource-example
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          ports:
            - name: http
              containerPort: 80
