apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-lab-01-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  hostPath:
    path: /tmp/storage-lab-01-data
    type: DirectoryOrCreate
