apiVersion: v1
kind: Pod
metadata:
  name: probe-methods-demo
spec:
  containers:
    - name: web
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
      readinessProbe:
        tcpSocket:
          port: 80
        periodSeconds: 5
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - test -f /usr/share/nginx/html/index.html
        periodSeconds: 10
