deployment:
  replicas: 1

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: false
  kubernetesGateway:
    enabled: false

service:
  spec:
    type: NodePort

ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443

log:
  level: INFO

accessLog:
  enabled: true
