apiVersion: v1
kind: LimitRange
metadata:
  name: container-resource-policy
  namespace: limitrange-lab-01
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 128Mi
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      min:
        cpu: 50m
        memory: 32Mi
      max:
        cpu: 500m
        memory: 256Mi
      maxLimitRequestRatio:
        cpu: "4"
        memory: "4"
