apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-demo
  namespace: limitrange-lab-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-demo
  template:
    metadata:
      labels:
        app: policy-demo
    spec:
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
