apiVersion: v1
kind: Pod
metadata:
  name: rbac-client
  namespace: rbac-lab-01
  labels:
    app: rbac-client
spec:
  serviceAccountName: pod-reader
  containers:
    - name: client
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - sleep 3600
      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          cpu: 20m
          memory: 32Mi
  restartPolicy: Always
