apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-storage-range
  namespace: example-namespace
spec:
  limits:
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 10Gi
