apiVersion: v1
kind: Namespace
metadata:
  name: quota-object-example
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-count-quota
  namespace: quota-object-example
spec:
  hard:
    pods: "10"
    services: "5"
    configmaps: "10"
    secrets: "10"
    persistentvolumeclaims: "4"
    count/deployments.apps: "3"
