apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: statefulset-lab-01
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
