apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
  namespace: ingress-lab
spec:
  rules:
    - host: ingress-lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-demo-service
                port:
                  number: 80
