apiVersion: v1
kind: Service
metadata:
  name: ingress-demo-service
  namespace: ingress-lab
spec:
  type: ClusterIP
  selector:
    app: ingress-demo
  ports:
    - name: http
      port: 80
      targetPort: http
