apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: networkpolicy-lab-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo "api response from $HOSTNAME" > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;'
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 48Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: networkpolicy-lab-01
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 80
      targetPort: http
